### ISSUE TITLE
[BUG] - generated uml vocabulary is missing some associations.

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/ecore-adapter#13]
## Steps to Reproduce
- [ ] ecoreToOml
- [ ] open build\oml\www.eclipse.org\uml2\5.0.0\UML.oml
- [ ] There are at least 3 association missing.
  See UML 2.5.1 spec, section 8.5.2, figure 8.4
  The following composite associations are missing in the generated OML:
  IntervalConstraint -> Interval
  TimeConstraint -> TimeInterval
  DurationConstraint -> DurationInterval

## Expected Behavior
A clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
These associations now show up in the latest revision of the UML ontology as restrictions on Constraint::specification. E.g.

	concept IntervalConstraint :> Constraint [
		restricts all relation constraint_specification to Interval
	]
	concept TimeConstraint :> IntervalConstraint [
		restricts all relation constraint_specification to TimeInterval
	]
	concept DurationConstraint :> IntervalConstraint [
		restricts all relation constraint_specification to DurationInterval
	]
